version: '3.8'

services:
  db:
    image: postgres:15
    container_name: travel_agency_db
    restart: always
    environment:
      POSTGRES_DB: travel_agency
      POSTGRES_USER: ${Database_Username}
      POSTGRES_PASSWORD: ${Database_Password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-network

networks:
  travel-network:
    external: true

volumes:
  postgres_data: